Lab 2 :AI

In [ ]:
import torch
import torch.nn as nn

linear1=nn.Linear(10,16)
linear2=nn.Linear(16,8)
linear3=nn.Linear(8,1)

linear1, linear2, linear3  # print

model = nn.Sequential(linear1, linear2, linear3)

model

Sequential(
  (0): Linear(in_features=10, out_features=16, bias=True)
  (1): Linear(in_features=16, out_features=8, bias=True)
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [ ]:
torch.manual_seed(42)
input1 = torch.randn(10)   # input to the model (fixed set of random numbers for reproducibility)
input1

tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,
         0.4617,  0.2674])

In [ ]:
output = model(input1)
print(output)

tensor([0.2074], grad_fn=<ViewBackward0>)


In [ ]:
## TO DO
output1 = linear1(input1)
print(output1)

output1.shape

tensor([-0.6228, -0.4053, -0.5502,  0.1361, -0.5146, -0.2349,  0.7056, -0.8312,
         0.6219, -0.3404, -0.8368, -0.6655, -0.8294,  0.7926,  0.4036,  0.2438],
       grad_fn=<ViewBackward0>)


torch.Size([16])

In [ ]:
output2=linear2(output1)
print(output2)

tensor([-0.5265, -0.0196,  0.0950,  0.1806,  0.1513,  0.2473,  0.0415, -0.6916],
       grad_fn=<ViewBackward0>)


In [ ]:
output3=linear3(output2)
print(output2)

tensor([-0.5265, -0.0196,  0.0950,  0.1806,  0.1513,  0.2473,  0.0415, -0.6916],
       grad_fn=<ViewBackward0>)


In [ ]:
print(linear1.weight)

Parameter containing:
tensor([[ 0.1125, -0.2633, -0.3067, -0.1641,  0.2165, -0.2977, -0.2753,  0.1772,
          0.1706,  0.2601],
        [-0.2387, -0.2314,  0.1622,  0.2750,  0.1892,  0.0495,  0.1042,  0.3001,
         -0.2040, -0.1436],
        [ 0.2212, -0.2164, -0.1744,  0.2308,  0.0998,  0.1022, -0.1340, -0.0044,
          0.2894, -0.1898],
        [ 0.0025,  0.1504, -0.2183,  0.3071, -0.1580, -0.0759, -0.0856, -0.2061,
         -0.3103,  0.1783],
        [ 0.0840, -0.2962, -0.2035,  0.3125,  0.1209,  0.1269, -0.1892, -0.1386,
         -0.0477, -0.0578],
        [-0.2167,  0.0261,  0.0314, -0.0400,  0.0438, -0.1253,  0.0823,  0.1193,
         -0.1666, -0.3136],
        [ 0.1655,  0.0754, -0.1608,  0.3047, -0.1430,  0.2137,  0.1604, -0.2651,
          0.2039, -0.2908],
        [-0.1752, -0.0527, -0.2132,  0.3089, -0.0634,  0.1256, -0.2824,  0.1820,
         -0.0983, -0.2405],
        [ 0.0462,  0.1532,  0.2737, -0.1931, -0.1556,  0.0608,  0.0858,  0.1216,
          0.1736, -0.0717

New ML pipeline

In [ ]:
#creating a toy dataset

from sklearn.datasets import make_classification

X, y = make_classification(n_samples=5000, n_features=10, n_redundant=0, n_informative=3, n_clusters_per_class=2, n_classes=2)


In [ ]:
print(X.shape)
print(y.shape)

(5000, 10)
(5000,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
import numpy as np
print(np.unique(y_train))

[0 1]


In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(4000, 10)
(4000,)
(1000, 10)
(1000,)


In [ ]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):

    # method to initialize dataset, and conversion to tensor
    def __init__(self, X_train, y_train):
        self.X = torch.from_numpy(X_train.astype(np.float32))
        self.y = torch.from_numpy(y_train).type(torch.LongTensor)
        self.len = self.X.shape[0]

    # method to return a single sample from the dataset given an index.
    def __getitem__(self, index):
        return self.X[index], self.y[index]

    # method to return the number of samples in the dataset.
    def __len__(self):
        return self.len


In [ ]:
print(X_train[25])                                     # simple access

traindata = CustomDataset(X_train, y_train)
print(traindata[25])                                   # access with above class' method

[ 0.54606382  0.12472337  0.19401565  2.32136859 -0.53377471 -0.25878372
 -1.58237825 -1.15995116  0.20615835 -2.0164373 ]
(tensor([ 0.5461,  0.1247,  0.1940,  2.3214, -0.5338, -0.2588, -1.5824, -1.1600,
         0.2062, -2.0164]), tensor(0))


In [ ]:
from torch.utils.data import DataLoader

trainloader = DataLoader(traindata, batch_size = 4)

In [ ]:
# Iterate through the TrainLoader

for batch_X, batch_y in trainloader:
    print(batch_X.shape, batch_y.shape)

torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Size([4])
torch.Size([4, 10]) torch.Si

Model

In [ ]:
class Network(nn.Module):

    # Define the layers and all in the constructor.
    def __init__(self):
        super(Network, self).__init__()  # Initialize parent class within the constructor
        self.linear1 = nn.Linear(10, 16)
        self.leaky_relu = nn.LeakyReLU()
        self.linear2 = nn.Linear(16, 8)
        self.sigmoid = nn.Sigmoid()
        self.linear3 = nn.Linear(8, 2)
        self.softmax = nn.Softmax(dim=-1)

    # Method for forward pass
    def forward(self, x):
        x = self.linear1(x)
        x = self.leaky_relu(x)
        x = self.linear2(x)  # Pass input to the linear2 layer
        x = self.sigmoid(x)  # Pass input to the sigmoid layer
        x = self.linear3(x)  # Pass input to the linear3 layer
        x = self.softmax(x)  # Pass input to the softmax layer
        return x

In [ ]:
model3 = Network()
print(model3)

Network(
  (linear1): Linear(in_features=10, out_features=16, bias=True)
  (leaky_relu): LeakyReLU(negative_slope=0.01)
  (linear2): Linear(in_features=16, out_features=8, bias=True)
  (sigmoid): Sigmoid()
  (linear3): Linear(in_features=8, out_features=2, bias=True)
  (softmax): Softmax(dim=-1)
)


In [ ]:
criterion = nn.CrossEntropyLoss()
print(criterion)

CrossEntropyLoss()


In [ ]:
import torch.optim as optim

optimizer = optim.Adam(model3.parameters(), lr = 0.001)
print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)


In [ ]:
num_epochs = 10
epoch_loss = []

for epoch in range(num_epochs):
  train_loss = 0
  for batch_X, batch_y in trainloader:
    optimizer.zero_grad()
    predicted = model3(batch_X)                      # forward pass in batches
    loss = criterion(predicted, batch_y)
    loss.backward()                                  # gradient calculation with help of loss
    optimizer.step()                                 # weight update

    # Evaluation example
    train_loss += loss.item()

    # After processing all batches, calculate average loss for the epoch
    average_loss = train_loss / len(trainloader)
    epoch_loss.append(average_loss)

  print(f'Epoch {epoch+1}/{num_epochs}, Loss: {average_loss}')


Epoch 1/10, Loss: 0.5637506052553654
Epoch 2/10, Loss: 0.45107432678341863
Epoch 3/10, Loss: 0.4378530102968216
Epoch 4/10, Loss: 0.4277526928782463
Epoch 5/10, Loss: 0.41609845238924026
Epoch 6/10, Loss: 0.406256455719471
Epoch 7/10, Loss: 0.4002104548811913
Epoch 8/10, Loss: 0.39687148106098175
Epoch 9/10, Loss: 0.3943797381818295
Epoch 10/10, Loss: 0.3924740240573883


In [ ]:
# save the trained model
PATH = './mymodel.pth'
torch.save(model3.state_dict(), PATH)

In [ ]:
# Loading the saved model
model3 = Network()
model3.load_state_dict(torch.load(PATH))

<All keys matched successfully>

In [ ]:
testdata = CustomDataset(X_test, y_test)

testloader = DataLoader(testdata, batch_size=4, shuffle=True, num_workers=2)

In [ ]:
print(testdata[5])
print(testloader)

(tensor([ 0.5423, -1.1086,  0.4119,  1.4052, -0.4650,  1.6066, -1.0118,  0.4604,
        -0.0631, -0.8726]), tensor(0))


In [ ]:
# Function to perform inference
def test_model(model, testloader):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    total = 0
    with torch.no_grad():  # Disable gradient calculation
        for batch_X, batch_y in testloader:
            outputs = model(batch_X)  # Perform forward pass
            _, predicted = torch.max(outputs, 1)  # Max probability value discarded, index obtained in predicted. [since output = (probability, class), here "class" is the index]
            total += batch_y.size(0)              # total no of samples so far
            correct += (predicted == batch_y).sum().item()     # total correct prediction so far. [(predicted==batch_y) is a boolean tensor, .sums true value in tensor, .item() converts the sum to scalar to give total true values.

    accuracy = correct / total
    print(f'Test Accuracy: {accuracy * 100:.2f}%')

In [ ]:
# Test the model
test_model(model3, testloader)

Test Accuracy: 93.00%


In [ ]:
from IPython import get_ipython
import IPython

def combine_code_cells():
    ipython = get_ipython()
    notebook_cells = ipython.user_ns['_ih']  # List of all executed input cells
    combined_code = ""

    for cell_code in notebook_cells:
        if cell_code.strip() and not cell_code.startswith('%') and not 'combine_code_cells' in cell_code:
            combined_code += cell_code.strip() + '\n\n'

    # Display the combined code
    print("----- Combined Code Start -----\n")
    print(combined_code)
    print("----- Combined Code End -----")

    # Optionally, copy to clipboard (Colab doesn't allow direct clipboard access from Python)
    # You can manually copy from the output cell
    return combined_code

# Run this function
combine_code_cells()


----- Combined Code Start -----

function combineCodeCells() {
  const cells = document.querySelectorAll('colab-run-button + div .inputarea');
  let combinedCode = '';
  cells.forEach(cell => {
    combinedCode += cell.innerText + '\n';
  });
  navigator.clipboard.writeText(combinedCode).then(() => {
    alert("All code copied to clipboard!");
  });
}
combineCodeCells();

def combineCodeCells() {
  const cells = document.querySelectorAll('colab-run-button + div .inputarea');
  let combinedCode = '';
  cells.forEach(cell => {
    combinedCode += cell.innerText + '\n';
  });
  navigator.clipboard.writeText(combinedCode).then(() => {
    alert("All code copied to clipboard!");
  });
}
combineCodeCells();

import torch
import torch.nn as nn

linear1=nn.Linear(10,16)
linear2=nn.Linear(16,8)
linear3=nn.Linear(8,1)

linear1, linear2, linear3  # print

model = nn.Sequential(linear1, linear2, linear3)

model

torch.manual_seed(42)
input1 = torch.randn(10)   # input to the model (fixed set of ra

'function combineCodeCells() {\n  const cells = document.querySelectorAll(\'colab-run-button + div .inputarea\');\n  let combinedCode = \'\';\n  cells.forEach(cell => {\n    combinedCode += cell.innerText + \'\\n\';\n  });\n  navigator.clipboard.writeText(combinedCode).then(() => {\n    alert("All code copied to clipboard!");\n  });\n}\ncombineCodeCells();\n\ndef combineCodeCells() {\n  const cells = document.querySelectorAll(\'colab-run-button + div .inputarea\');\n  let combinedCode = \'\';\n  cells.forEach(cell => {\n    combinedCode += cell.innerText + \'\\n\';\n  });\n  navigator.clipboard.writeText(combinedCode).then(() => {\n    alert("All code copied to clipboard!");\n  });\n}\ncombineCodeCells();\n\nimport torch\nimport torch.nn as nn\n\nlinear1=nn.Linear(10,16)\nlinear2=nn.Linear(16,8)\nlinear3=nn.Linear(8,1)\n\nlinear1, linear2, linear3  # print\n\nmodel = nn.Sequential(linear1, linear2, linear3)\n\nmodel\n\ntorch.manual_seed(42)\ninput1 = torch.randn(10)   # input to the mo